package com.example.weathercheck;

import android.Manifest;
import android.content.Context;
import android.content.pm.PackageManager;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.JsonHttpResponseHandler;
import com.loopj.android.http.RequestParams;

import org.json.JSONObject;

import cz.msebera.android.httpclient.Header;


public class WeatherController extends AppCompatActivity {


    final String WEATHER_URL = "http://api.openweathermap.org/data/2.5/weather";
    final String APP_ID = "7ace2123455c22e58d3f8e7ce076dd75";
    // Time between location updates (5000 milliseconds or 5 seconds)
    final long MIN_TIME = 5000;
    // Distance between location updates (1000m or 1km)
    final float MIN_DISTANCE = 1000;
    //permission code for location access
    final int REQUEST_CODE = 1234;
    String LOCATION_PROVIDER = LocationManager.GPS_PROVIDER;

    TextView mCityLabel;
    ImageView mWeatherImage;
    TextView mTemperatureLabel;

    LocationManager locationManager;
    LocationListener locationListener;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.weather_controller_layout);

        mCityLabel = (TextView) findViewById(R.id.locationTV);
        mWeatherImage = (ImageView) findViewById(R.id.weatherSymbolIV);
        mTemperatureLabel = (TextView) findViewById(R.id.tempTV);
        ImageButton changeCityButton = (ImageButton) findViewById(R.id.changeCityButton);

    }


    @Override
    protected void onResume() {
        super.onResume();
        Log.d("WeatherApp", "onResume() called.");
        Log.d("WeatherApp", "retrieving GPS location...");
        getWeatherForCurrentLocation();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        String result;
        if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                getWeatherForCurrentLocation();
            } else if (grantResults[0] == PackageManager.PERMISSION_DENIED) {
                // Permission Denied
                if (ActivityCompat.shouldShowRequestPermissionRationale(this,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
                    finish();
                } else {
                    finish();
                }
            }
        }


    private void getWeatherForCurrentLocation() {
        locationManager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
        locationListener = new LocationListener() {
            @Override
            public void onLocationChanged(Location location) {
                Log.d("WeatherApp", "location changed, listener called.");

                String longitudeFound = String.valueOf(location.getLongitude());
                String latitudeFound = String.valueOf(location.getLatitude());

                RequestParams params = new RequestParams();
                params.put("lat", latitudeFound);
                params.put("long", longitudeFound);
                params.put("appid", APP_ID);

                sendLocationDetailsToOpenWeather(params);
            }

            @Override
            public void onStatusChanged(String provider, int status, Bundle extras) {
            }
            @Override
            public void onProviderEnabled(String provider) {
            }
            @Override
            public void onProviderDisabled(String provider) {
                Log.d("WeatherApp", "provider disabled. onProviderDisabled() called. ");
            }
        };

        //checks for permission, gives a popup box. Generated by Android Studio, on error when using locationManager.requestLocationUpdates. Started since Nougat.
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            // here to request the missing permissions, and then overriding
            //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
            //                                          int[] grantResults)
            // to handle the case where the user grants the permission. See the documentation
            // for ActivityCompat#requestPermissions for more details.

            //calling requestpermission first:
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, REQUEST_CODE);
            //now wait until user grants permission/denies it. Basically waiting for an event to be triggered from user. Overriding
            //onRequestPermissionsResult elsewhere which will take care of this event trigger.
            return;
        }
            locationManager.requestLocationUpdates(LOCATION_PROVIDER, MIN_TIME, MIN_DISTANCE, locationListener);
    }


        private void sendLocationDetailsToOpenWeather(RequestParams params){
            AsyncHttpClient client = new AsyncHttpClient();

            client.get(WEATHER_URL, params, new JsonHttpResponseHandler(){
                //this method recieves one of two handlers, onSuccess or onFailure dependiing on HTTP response success
                @Override
                public void onSuccess(int statusCode, Header[] headers, JSONObject response){
                    Log.e("WeatherApp", "success! JSON: "+ response.toString());
                    WeatherDataModel weatherData = WeatherDataModel.fromJSON(response);
                    updateUIwithWeatherDetail(weatherData);
                }
                @Override
                public void onFailure(int statusCode, Header[] headers, Throwable e, JSONObject response){
                    Log.e("WeatherApp", e.toString());
                    Log.e("WeatherApp", "status code : "+statusCode);
                    Toast.makeText(WeatherController.this, "Request to fetch location failed!", Toast.LENGTH_SHORT).show();

                }
            });
        }


        private void updateUIwithWeatherDetail(WeatherDataModel weather){
           mTemperatureLabel.setText(weather.getmTemperature());
           mCityLabel.setText(weather.getmCity());

           int resourceIDforIcon = getResources().getIdentifier(weather.getmIconName(), "drawable", getPackageName());
           mWeatherImage.setImageResource(resourceIDforIcon);

        }




}

